[book]
title = "The Move Social — Corporate Docs"
authors = ["Altin Lecaj", "Eric Garcia"]
language = "en"
src = "."

[build]
build-dir = "_build"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/letemcook/the-move-biz"
additional-css = ["theme/custom.css"]
no-section-label = true
